### ISSUE TITLE
prototype

### ISSUE THREAD

**Issue by yegor256** [objectionary/sot#1]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2](https://github.com/objectionary/sot/issues/2) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#2](https://github.com/objectionary/sot/issues/2), [#3](https://github.com/objectionary/sot/issues/3) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2](https://github.com/objectionary/sot/issues/2) is still not solved; solved: [#3](https://github.com/objectionary/sot/issues/3).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#6](https://github.com/objectionary/sodg/issues/6) is still not solved.
