### ISSUE TITLE
lib.rs:21-23: For some weird reason, if I enable this...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/sot#3]
The puzzle `1-3b40c6f3` from #1 has to be resolved: 

https://github.com/objectionary/sot/blob/769ab71a951748c6697a5faefccf365c9cd47343/src/lib.rs#L21-L23

The puzzle was created by @yegor256 on 04-Oct-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@levBagryansky please, try to help

**Comment by 0pdd** [comment]
The puzzle `1-3b40c6f3` has disappeared from the source code, that's why I closed this issue.
